name: 🧰 Upgrade LLVM
inputs:
  os:
    required: true
runs:
  using: composite
  steps:
    - name: 🍺 Brewing
      if: inputs.os == 'ubuntu-latest'
      shell: bash
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install llvm
    - name: 🔎 Check Clang Version
      if: inputs.os == 'ubuntu-latest'
      shell: bash
      run: /home/linuxbrew/.linuxbrew/bin/clang++ -v  

    - name: 🍺 Brewing
      if: inputs.os == 'macos-latest'
      shell: bash
      run: brew install llvm
    - name: 🔎 Check Clang Version
      if: inputs.os == 'macos-latest'
      shell: bash
      run: /usr/local/opt/llvm/bin/clang++ -v  

    - name: 🍫 Brewing
      if: inputs.os == 'windows-latest'
      shell: pwsh
      run: choco upgrade llvm -y
    - name: 🔎 Check Clang Version
      if: inputs.os == 'windows-latest'
      shell: pwsh
      run: clang++ -v  
