name: 🧰 Setup Enviroment
inputs:
  os:
    required: true
  cwd:
    default: .
runs:
  using: composite
  steps:
    - name: 🛒 Checkout ECOW
      uses: actions/checkout@v3
      with:
        repository: m4c0/ecow
        path: ecow

    - name: ⚙️  Install WASI
      if: inputs.os == 'macos-latest'
      shell: bash
      run: |
        wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-17/wasi-sysroot-17.0.tar.gz
        tar xfv wasi-sysroot-17.0.tar.gz
        wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-17/libclang_rt.builtins-wasm32-wasi-17.0.tar.gz
        cd wasi-sysroot
        tar xvf ../libclang_rt.builtins-wasm32-wasi-17.0.tar.gz
      working-directory: ${{ inputs.cwd }}

    # Not needed for now, since GHA provides LLVM 15 now
    # - name: 🍺 Brewing
    #   if: inputs.os == 'macos-latest'
    #   shell: bash
    #   run: brew install llvm
    - name: 🔎 Check Clang Version
      if: inputs.os == 'macos-latest'
      shell: bash
      run: /usr/local/opt/llvm/bin/clang++ -v  

    # Not needed for now, since GHA provides LLVM 15 now
    # - name: 🍫 Brewing
    #   if: inputs.os == 'windows-latest'
    #   shell: pwsh
    #   run: choco upgrade llvm -y
    - name: 🔎 Check Clang Version
      if: inputs.os == 'windows-latest'
      shell: pwsh
      run: clang++ -v  
