name: 🔨 Build with ECOW
inputs:
  project:
    required: true

runs:
  using: composite
  steps:
    - name: Build ECOW Meta-builder
      shell: bash
      working-directory: ecow
      run: clang++ -std=c++20 build.cpp -o build.exe
    - name: Run ECOW Meta-builder
      shell: bash
      working-directory: ecow
      run: ./build.exe
    - name: 🐮 Build ECOW
      shell: bash
      working-directory: ${{ inputs.project }}
      run: $GITHUB_WORKSPACE/ecow/build.exe

    - name: 🍼 Build Project
      if: runner.os == 'macOS'
      shell: bash
      working-directory: ${{ inputs.project }}
      run: ./build clean macosx iphoneos iphonesimulator wasm android

    - name: 🍼 Build Project
      if: runner.os == 'Windows'
      shell: pwsh
      working-directory: ${{ inputs.project }}
      run: ./build.exe clean windows
