name: 🔨 Build with ECOW
inputs:
  project:
    required: true

runs:
  using: composite
  steps:
    - name: 🐮 Build ECOW
      if: runner.os == 'macOS'
      shell: bash
      working-directory: ${{ inputs.project }}
      run: clang++ -I../ecow -std=c++20 build.cpp -o build.exe
    - name: 🍼 Build Project
      if: runner.os == 'macOS'
      shell: bash
      working-directory: ${{ inputs.project }}
      run: ./build.exe macosx iphoneos iphonesimulator wasm android

    - name: 🐮 Build ECOW
      if: runner.os == 'Windows'
      shell: pwsh
      working-directory: ${{ inputs.project }}
      run: clang++ -I../ecow -std=c++20 build.cpp -o build.exe
    - name: 🍼 Build Project
      if: runner.os == 'Windows'
      shell: pwsh
      working-directory: ${{ inputs.project }}
      run: ./build.exe
