name: proof-of-concept
on: 
  workflow_dispatch:
  push:
  pull_request:

concurrency:
  group: ecow-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linus:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
      - name: 🍺 Brewing LLVM
        uses: m4c0/ecow/.github/actions/upgrade_llvm@main
        with:
          os: ubuntu-latest
          cwd: poc
      - run: clang++ -std=c++20 build.cpp -o build.exe
        working-directory: poc/a-nostl
      - run: ./build.exe wasm android
        working-directory: poc/a-nostl
      - run: clang++ -std=c++20 build.cpp -o build.exe
        working-directory: poc/b-nostl
      - run: ./build.exe wasm android
        working-directory: poc/b-nostl
  steve:
    runs-on: macos-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
      - name: 🍺 Brewing LLVM
        uses: m4c0/ecow/.github/actions/upgrade_llvm@main
        with:
          os: macos-latest
      - run: clang++ -std=c++20 build.cpp -o build.exe
        working-directory: poc/a-nostl
      - run: ./build.exe macosx iphoneos
        working-directory: poc/a-nostl
      - run: clang++ -std=c++20 build.cpp -o build.exe
        working-directory: poc/b-nostl
      - run: ./build.exe macosx iphoneos
        working-directory: poc/b-nostl
  bill:
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
      - name: 🍺 Brewing LLVM
        uses: m4c0/ecow/.github/actions/upgrade_llvm@main
        with:
          os: windows-latest
      - run: clang++ -std=c++20 build.cpp -o build.exe
        working-directory: poc/a-nostl
      - run: .\build.exe
        working-directory: poc/a-nostl
      - run: clang++ -std=c++20 build.cpp -o build.exe
        working-directory: poc/b-nostl
      - run: .\build.exe
        working-directory: poc/b-nostl
