name: proof-of-concept
on: 
  workflow_dispatch:
  push:
  pull_request:

jobs:
  # oreo:
  #   runs-on: ubuntu-latest
  #   env:
  #     CXX: clang++-15
  #   steps:
  #     - run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
  #     - run: clang++-15 -v
  #     - uses: actions/checkout@v3
  #     - run: clang++-15 -std=c++20 build.cpp -o build.exe
  #     - run: ./build.exe android
  steve:
    runs-on: macos-latest
    steps:
      - run: brew install llvm
      - run: /usr/local/opt/llvm/bin/clang++ -v  
      - uses: actions/checkout@v3
      - run: clang++ -std=c++20 build.cpp -o build.exe
        working-directory: poc/a
      - run: ./build.exe macosx iphoneos
        working-directory: poc/a
      - run: clang++ -std=c++20 build.cpp -o build.exe
        working-directory: poc/b
      - run: ./build.exe macosx iphoneos
        working-directory: poc/b
  bill:
    runs-on: windows-latest
    steps:
      - run: choco upgrade llvm -y
      - run: clang++ -v  
      - uses: actions/checkout@v3
      - run: clang++ -std=c++20 build.cpp -o build.exe
        working-directory: poc/a
      - run: .\build.exe
        working-directory: poc/a
      - run: clang++ -std=c++20 build.cpp -o build.exe
        working-directory: poc/b
      - run: .\build.exe
        working-directory: poc/b
