name: proof-of-concept
on: 
  workflow_dispatch:
  push:
  pull_request:

jobs:
  linus:
    runs-on: ubuntu-latest
    env:
      CXX: clang++-15
    steps:
      - name: Upgrade LLVM
        run: 'sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"'
      - name: Print clang version
        run: clang++ -v  
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the builder
        run: clang++ -std=c++20 build-poc.cpp -o build
      - name: Run the builder
        run: ./build
  steve:
    runs-on: macos-latest
    env:
      CXX: /usr/local/opt/llvm/bin/clang++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
    steps:
      - name: Upgrade LLVM
        run: brew install llvm
      - name: Print clang version
        run: /usr/local/opt/llvm/bin/clang++ -v  
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile the builder
        run: $CXX -std=c++20 build-poc.cpp -c -o build.o
      - name: Link the builder
        run: clang++ -o build build.o
      - name: Run the builder
        run: ./build
  bill:
    runs-on: windows-latest
    steps:
      - name: Upgrade LLVM
        run: choco upgrade llvm -y
      - name: Print clang version
        run: clang++ -v  
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the builder
        run: clang++ -std=c++20 build-poc.cpp -o build.exe
      - name: Run the builder
        run: .\build.exe
