name: proof-of-concept
on: 
  workflow_dispatch:
  push:
  pull_request:

concurrency:
  group: ecow-${{ github.ref }}
  cancel-in-progress: true

jobs:
  oreo:
    runs-on: ubuntu-latest
    steps:
      - uses: m4c0/ecow/.github/actions/upgrade_llvm@main
        with:
          os: ubuntu-latest
      - uses: actions/checkout@v3
      - run: |
          cd poc
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-17/wasi-sysroot-17.0.tar.gz
          tar xfv wasi-sysroot-17.0.tar.gz
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-17/libclang_rt.builtins-wasm32-wasi-17.0.tar.gz
          cd wasi-sysroot
          tar xvf ../libclang_rt.builtins-wasm32-wasi-17.0.tar.gz
      - run: clang++ -std=c++20 build.cpp -o build.exe
        working-directory: poc/a-nostl
      - run: ./build.exe wasm android
        working-directory: poc/a-nostl
      - run: clang++ -std=c++20 build.cpp -o build.exe
        working-directory: poc/b-nostl
      - run: ./build.exe wasm android
        working-directory: poc/b-nostl
  steve:
    runs-on: macos-latest
    steps:
      - uses: m4c0/ecow/.github/actions/upgrade_llvm@main
        with:
          os: macos-latest
      - uses: actions/checkout@v3
      - run: clang++ -std=c++20 build.cpp -o build.exe
        working-directory: poc/a-nostl
      - run: ./build.exe macosx iphoneos
        working-directory: poc/a-nostl
      - run: clang++ -std=c++20 build.cpp -o build.exe
        working-directory: poc/b-nostl
      - run: ./build.exe macosx iphoneos
        working-directory: poc/b-nostl
  bill:
    runs-on: windows-latest
    steps:
      - uses: m4c0/ecow/.github/actions/upgrade_llvm@main
        with:
          os: windows-latest
      - uses: actions/checkout@v3
      - run: clang++ -std=c++20 build.cpp -o build.exe
        working-directory: poc/a-nostl
      - run: .\build.exe
        working-directory: poc/a-nostl
      - run: clang++ -std=c++20 build.cpp -o build.exe
        working-directory: poc/b-nostl
      - run: .\build.exe
        working-directory: poc/b-nostl
