name: proof-of-concept
on: 
  workflow_dispatch:
  push:
  pull_request:

concurrency:
  group: ecow-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-pocs:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: 🧰 Setup
        uses: m4c0/ecow/.github/actions/setup@main
        with:
          os: ${{ matrix.os }}
          cwd: ecow/poc
      - name: 🔨 Build POC A
        uses: m4c0/ecow/.github/actions/compile@main
        with:
          os: ${{ matrix.os }}
          project: ecow/poc/a-nostl
      - name: 🔨 Build POC B
        uses: m4c0/ecow/.github/actions/compile@main
        with:
          os: ${{ matrix.os }}
          project: ecow/poc/b-nostl
      - name: 🔨 Build Tooling POC
        uses: m4c0/ecow/.github/actions/compile@main
        with:
          os: ${{ matrix.os }}
          project: ecow/poc/tooling
