name: proof-of-concept
on: 
  workflow_dispatch:
  push:
  pull_request:

jobs:
  linus:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade LLVM
        run: 'sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"'
      - name: Print clang version
        run: clang++ -v  
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the builder
        run: clang++ -std=c++20 build-poc.cpp -o build
      - name: Run the builder
        run: ./build
      - name: Run the proof-of-concept
        run: ./a.exe
  steve:
    runs-on: macos-latest
    env:
      CXX: /usr/local/opt/llvm/bin/clang++ -isysroot $(xcrun --show-sdk-path)
    steps:
      - name: Upgrade LLVM
        run: brew install llvm
      - name: Print clang version
        run: /usr/local/opt/llvm/bin/clang++ -v  
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile the builder
        run: $CXX -std=c++20 build-poc.cpp -o build-poc.o
      - name: Link the builder
        run: clang++ -o build-poc build-poc.o
      - name: Run the builder
        run: ./build.poc
      - name: Run the proof-of-concept
        run: ./a.exe
  bill:
    runs-on: windows-latest
    steps:
      - name: Upgrade LLVM
        run: choco upgrade llvm -y
      - name: Print clang version
        run: clang++ -v  
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the builder
        run: clang++ -std=c++20 build-poc.cpp -o build.exe
      - name: Run the builder
        run: .\build.exe
      - name: Run the proof-of-concept
        run: .\a.exe
