name: proof-of-concept
on: 
  workflow_dispatch:
  push:
  pull_request:

jobs:
  steve:
    runs-on: macos-latest
    steps:
      - run: brew install llvm
      - run: /usr/local/opt/llvm/bin/clang++ -v  
      - uses: actions/checkout@v3
      - run: clang++ -std=c++20 build-poc.cpp -o build.exe
      - run: ./build.exe
  bill:
    runs-on: windows-latest
    steps:
      - run: choco upgrade llvm -y
      - run: clang++ -v  
      - uses: actions/checkout@v3
      - run: clang++ -std=c++20 build-poc.cpp -o build.exe
      - run: .\build.exe
